[package]
name = "common-exceptions"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
anyhow = "1.0.58"
backoff = { version = "0.4.0", features = ["futures", "tokio"] }
tokio = { version = "1.19.2", features = ["full"] }


[dev-dependencies]
