[build.env]
passthrough = [
    "BUILD_DIR",
    "CARGO_INCREMENTAL",
    "CARGO_PROFILE_RELEASE_OPT_LEVEL",
    "CARGO_PROFILE_RELEASE_CODEGEN_UNITS",
    "RUST_BACKTRACE",
    "RUST_LOG",
    "VECTOR_BUILD_DESC",
    "JEMALLOC_SYS_WITH_LG_PAGE",
    "JEMALLOC_SYS_WITH_LG_HUGEPAGE",
]

[target.aarch64-unknown-linux-gnu]
dockerfile = "./docker/cross/Dockerfile.aarch64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
dockerfile = "./docker/cross/Dockerfile.x86_64-unknown-linux-gnu"

[target.aarch64-unknown-linux-musl]
dockerfile = "./docker/cross/Dockerfile.aarch64-unknown-linux-musl"

[target.x86_64-unknown-linux-musl]
dockerfile = "./docker/cross/Dockerfile.x86_64-unknown-linux-musl"
